services:

    contributors.configuration.provider.cache:
        class: Doctrine\Common\Cache\PhpFileCache
        arguments:
            - '%kernel.cache_dir%/dist'

    contributors.configuration.povidere.cache_cleaner:
        class: ContributorsBundle\Cache\ContributorsCacheCleaner
        arguments:
            - '@contributors.configuration.provider.cache'
        tags:
            - { name: kernel.cache_clearer }

    contributors.configuration.provider:
        class: ContributorsBundle\Configuration\ConfigurationProvider
        public: true
        arguments:
            - '%kernel.bundles%'
            - '@contributors.configuration.provider.cache'
